# Generated by Django 3.2.5 on 2021-07-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
